#!/bin/sh /etc/rc.common

# Start late and stop early
START=99
STOP=80

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=0

start() {
        stop
        service_start /sbin/logd
}

stop() {
        service_stop /sbin/logd
}

