<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32pg23.prs" label="PRS" name="PRS" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="PRS.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="PRS.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="PRS.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="PRS.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="PRS.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH0.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH0_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch0_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH0.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH1.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH1_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch1_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH1.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH2.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH2_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch2_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH2.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH3.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH3_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch3_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH3.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH4.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH4_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch4_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH4.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH5.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH5_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch5_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH5.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH6.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH6_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch6_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH6.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH7.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH7_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch7_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH7.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH8.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH8_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch8_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH8.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH9.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH9_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch9_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH9.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH10.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH10_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch10_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH10.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH11.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH11_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="VDAC0L" value="VDAC0L"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="SYSRTC0" value="SYSRTC0"/>
        <enumValue label="LESENSE" value="LESENSE"/>
        <enumValue label="HFXO0L" value="HFXO0L"/>
        <enumValue label="EUSART0L" value="EUSART0L"/>
        <enumValue label="EUSART1L" value="EUSART1L"/>
        <enumValue label="EUSART2L" value="EUSART2L"/>
        <enumValue label="HFRCO0" value="HFRCO0"/>
        <enumValue label="HFRCOEM23" value="HFRCOEM23"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_VDAC0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VDAC0L_CH0WARM" value="VDAC0L_CH0WARM"/>
        <enumValue label="VDAC0L_CH1WARM" value="VDAC0L_CH1WARM"/>
        <enumValue label="VDAC0L_CH0DONEASYNC" value="VDAC0L_CH0DONEASYNC"/>
        <enumValue label="VDAC0L_CH1DONEASYNC" value="VDAC0L_CH1DONEASYNC"/>
        <enumValue label="VDAC0L_INTERNALTIMEROF" value="VDAC0L_INTERNALTIMEROF"/>
        <enumValue label="VDAC0L_REFRESHTIMEROF" value="VDAC0L_REFRESHTIMEROF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_SYSRTC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="SYSRTC0_GRP0OUT0" value="SYSRTC0_GRP0OUT0"/>
        <enumValue label="SYSRTC0_GRP0OUT1" value="SYSRTC0_GRP0OUT1"/>
        <enumValue label="SYSRTC0_GRP1OUT0" value="SYSRTC0_GRP1OUT0"/>
        <enumValue label="SYSRTC0_GRP1OUT1" value="SYSRTC0_GRP1OUT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_DECOUT0" value="LESENSE_DECOUT0"/>
        <enumValue label="LESENSE_DECOUT1" value="LESENSE_DECOUT1"/>
        <enumValue label="LESENSE_DECOUT2" value="LESENSE_DECOUT2"/>
        <enumValue label="LESENSE_DECCMP" value="LESENSE_DECCMP"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_HFXO0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFXO0L_STATUS" value="HFXO0L_STATUS"/>
        <enumValue label="HFXO0L_STATUS1" value="HFXO0L_STATUS1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_EUSART0L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART0L_CS" value="EUSART0L_CS"/>
        <enumValue label="EUSART0L_IRDATX" value="EUSART0L_IRDATX"/>
        <enumValue label="EUSART0L_RTS" value="EUSART0L_RTS"/>
        <enumValue label="EUSART0L_RXDATAV" value="EUSART0L_RXDATAV"/>
        <enumValue label="EUSART0L_TX" value="EUSART0L_TX"/>
        <enumValue label="EUSART0L_TXC" value="EUSART0L_TXC"/>
        <enumValue label="EUSART0L_RXFL" value="EUSART0L_RXFL"/>
        <enumValue label="EUSART0L_TXFL" value="EUSART0L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_EUSART1L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART1L_CS" value="EUSART1L_CS"/>
        <enumValue label="EUSART1L_IRDATX" value="EUSART1L_IRDATX"/>
        <enumValue label="EUSART1L_RTS" value="EUSART1L_RTS"/>
        <enumValue label="EUSART1L_RXDATAV" value="EUSART1L_RXDATAV"/>
        <enumValue label="EUSART1L_TX" value="EUSART1L_TX"/>
        <enumValue label="EUSART1L_TXC" value="EUSART1L_TXC"/>
        <enumValue label="EUSART1L_RXFL" value="EUSART1L_RXFL"/>
        <enumValue label="EUSART1L_TXFL" value="EUSART1L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_EUSART2L.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUSART2L_CS" value="EUSART2L_CS"/>
        <enumValue label="EUSART2L_IRDATX" value="EUSART2L_IRDATX"/>
        <enumValue label="EUSART2L_RTS" value="EUSART2L_RTS"/>
        <enumValue label="EUSART2L_RXDATAV" value="EUSART2L_RXDATAV"/>
        <enumValue label="EUSART2L_TX" value="EUSART2L_TX"/>
        <enumValue label="EUSART2L_TXC" value="EUSART2L_TXC"/>
        <enumValue label="EUSART2L_RXFL" value="EUSART2L_RXFL"/>
        <enumValue label="EUSART2L_TXFL" value="EUSART2L_TXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_HFRCO0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCO0_COREEN" value="HFRCO0_COREEN"/>
        <enumValue label="HFRCO0_STATE0" value="HFRCO0_STATE0"/>
        <enumValue label="HFRCO0_STATE1" value="HFRCO0_STATE1"/>
        <enumValue label="HFRCO0_STATE2" value="HFRCO0_STATE2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_HFRCOEM23.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="HFRCOEM23_COREEN" value="HFRCOEM23_COREEN"/>
        <enumValue label="HFRCOEM23_STATE0" value="HFRCOEM23_STATE0"/>
        <enumValue label="HFRCOEM23_STATE1" value="HFRCOEM23_STATE1"/>
        <enumValue label="HFRCOEM23_STATE2" value="HFRCOEM23_STATE2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch11_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH11.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="PRS">
        <subCategory label="">
          <propertyRef refId="PRS.usedbysdk.BOOL"/>
          <propertyRef refId="PRS.hiddenbysdk.BOOL"/>
          <propertyRef refId="PRS.showadvanced.BOOL"/>
          <propertyRef refId="PRS.forceenable.BOOL"/>
          <propertyRef refId="PRS.owner.STRING"/>
        </subCategory>
        <subCategory label="CH0 properties">
          <propertyRef refId="PRS.custom_name_CH0.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch0_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0.PIN"/>
        </subCategory>
        <subCategory label="CH1 properties">
          <propertyRef refId="PRS.custom_name_CH1.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch1_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1.PIN"/>
        </subCategory>
        <subCategory label="CH2 properties">
          <propertyRef refId="PRS.custom_name_CH2.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch2_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2.PIN"/>
        </subCategory>
        <subCategory label="CH3 properties">
          <propertyRef refId="PRS.custom_name_CH3.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch3_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3.PIN"/>
        </subCategory>
        <subCategory label="CH4 properties">
          <propertyRef refId="PRS.custom_name_CH4.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch4_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4.PIN"/>
        </subCategory>
        <subCategory label="CH5 properties">
          <propertyRef refId="PRS.custom_name_CH5.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch5_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5.PIN"/>
        </subCategory>
        <subCategory label="CH6 properties">
          <propertyRef refId="PRS.custom_name_CH6.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch6_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH6.PIN"/>
        </subCategory>
        <subCategory label="CH7 properties">
          <propertyRef refId="PRS.custom_name_CH7.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch7_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH7.PIN"/>
        </subCategory>
        <subCategory label="CH8 properties">
          <propertyRef refId="PRS.custom_name_CH8.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch8_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH8.PIN"/>
        </subCategory>
        <subCategory label="CH9 properties">
          <propertyRef refId="PRS.custom_name_CH9.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch9_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH9.PIN"/>
        </subCategory>
        <subCategory label="CH10 properties">
          <propertyRef refId="PRS.custom_name_CH10.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch10_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH10.PIN"/>
        </subCategory>
        <subCategory label="CH11 properties">
          <propertyRef refId="PRS.custom_name_CH11.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_VDAC0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_SYSRTC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_HFXO0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_EUSART0L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_EUSART1L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_EUSART2L.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_HFRCO0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_HFRCOEM23.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch11_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH11.PIN"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
