/*
 * Copyright 2016-2018 Ayla Networks, Inc.  All rights reserved.
 *
 * Use of the accompanying software is permitted only in accordance
 * with and subject to the terms of the Software License Agreement
 * with Ayla Networks, Inc., a copy of which can be obtained from
 * Ayla Networks, Inc.
 */

#ifndef __LIB_APP_MSG_CLIENT_H__
#define __LIB_APP_MSG_CLIENT_H__

struct amsg_endpoint;

/*
 * Return true if a connection to the cloud has been established.
 */
bool msg_client_cloud_up(void);

/*
 * Return true if a connection to at least one LAN client has been established.
 */
bool msg_client_lan_up(void);

/*
 * Return true if user registration has been completed.
 */
bool msg_client_registered(void);

/*
 * Return the most recently received user registration token, if known,
 * otherwise an empty string.
 */
const char *msg_client_regtoken(void);

/*
 * Return a handle to the connection to the cloud client.
 */
struct amsg_endpoint *msg_client_endpoint(void);

/*
 * Push a new setup token and/or location.  The setup token is generally
 * generated by a mobile app for use in device setup and registration.  The
 * location is informational, and may also be used to update the device's
 * timezone.
 */
int msg_client_setup_info_update(const char *token,
	const char *location);

/*
 * Start user registration window.  This is used with the push-button
 * registration method.
 */
int msg_client_reg_window_start(void);

/*
 * Initiate a factory reset on the entire system.
 */
int msg_client_global_factory_reset(void);

#endif /* __LIB_APP_MSG_CLIENT_H__ */
