################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
S79_SRCS += \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/faults.s79 \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/isr-stubs.s79 

C_SRCS += \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/assert-crash-handlers.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/cdc/callbacks.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/crc.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/cstartup-common.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/cdc/descriptors.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbd.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbdch9.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbdep.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbhal.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbint.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbtimer.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/endian.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/mem-util.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/mfg-token.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/micro-common.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/micro.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/mpu.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/random.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/sleep.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/token-def.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/token.c \
D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/uart.c 

OBJS += \
./hal-library/EM3588/assert-crash-handlers.o \
./hal-library/EM3588/callbacks.o \
./hal-library/EM3588/crc.o \
./hal-library/EM3588/cstartup-common.o \
./hal-library/EM3588/descriptors.o \
./hal-library/EM3588/em_usbd.o \
./hal-library/EM3588/em_usbdch9.o \
./hal-library/EM3588/em_usbdep.o \
./hal-library/EM3588/em_usbhal.o \
./hal-library/EM3588/em_usbint.o \
./hal-library/EM3588/em_usbtimer.o \
./hal-library/EM3588/endian.o \
./hal-library/EM3588/faults.o \
./hal-library/EM3588/isr-stubs.o \
./hal-library/EM3588/mem-util.o \
./hal-library/EM3588/mfg-token.o \
./hal-library/EM3588/micro-common.o \
./hal-library/EM3588/micro.o \
./hal-library/EM3588/mpu.o \
./hal-library/EM3588/random.o \
./hal-library/EM3588/sleep.o \
./hal-library/EM3588/token-def.o \
./hal-library/EM3588/token.o \
./hal-library/EM3588/uart.o 

S79_DEPS += \
./hal-library/EM3588/faults.d \
./hal-library/EM3588/isr-stubs.d 

C_DEPS += \
./hal-library/EM3588/assert-crash-handlers.d \
./hal-library/EM3588/callbacks.d \
./hal-library/EM3588/crc.d \
./hal-library/EM3588/cstartup-common.d \
./hal-library/EM3588/descriptors.d \
./hal-library/EM3588/em_usbd.d \
./hal-library/EM3588/em_usbdch9.d \
./hal-library/EM3588/em_usbdep.d \
./hal-library/EM3588/em_usbhal.d \
./hal-library/EM3588/em_usbint.d \
./hal-library/EM3588/em_usbtimer.d \
./hal-library/EM3588/endian.d \
./hal-library/EM3588/mem-util.d \
./hal-library/EM3588/mfg-token.d \
./hal-library/EM3588/micro-common.d \
./hal-library/EM3588/micro.d \
./hal-library/EM3588/mpu.d \
./hal-library/EM3588/random.d \
./hal-library/EM3588/sleep.d \
./hal-library/EM3588/token-def.d \
./hal-library/EM3588/token.d \
./hal-library/EM3588/uart.d 


# Each subdirectory must supply rules for building sources it contributes
hal-library/EM3588/assert-crash-handlers.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/assert-crash-handlers.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/assert-crash-handlers.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/callbacks.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/cdc/callbacks.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/callbacks.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/crc.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/crc.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/crc.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/cstartup-common.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/cstartup-common.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/cstartup-common.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/descriptors.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/cdc/descriptors.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/descriptors.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/em_usbd.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbd.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/em_usbd.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/em_usbdch9.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbdch9.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/em_usbdch9.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/em_usbdep.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbdep.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/em_usbdep.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/em_usbhal.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbhal.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/em_usbhal.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/em_usbint.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbint.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/em_usbint.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/em_usbtimer.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/usb/em_usbtimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/em_usbtimer.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/endian.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/endian.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/endian.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/faults.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/faults.s79
	@echo 'Building file: $<'
	@echo 'Invoking: IAR Assembler for ARM'
	iasmarm "$<" -o  "$@" --cpu Cortex-M3 --fpu None -s+ -r -L -N -p80 -t2 -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' -E100
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/isr-stubs.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/isr-stubs.s79
	@echo 'Building file: $<'
	@echo 'Invoking: IAR Assembler for ARM'
	iasmarm "$<" -o  "$@" --cpu Cortex-M3 --fpu None -s+ -r -L -N -p80 -t2 -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' -E100
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/mem-util.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/mem-util.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/mem-util.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/mfg-token.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/mfg-token.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/mfg-token.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/micro-common.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/micro-common.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/micro-common.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/micro.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/micro.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/micro.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/mpu.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/mpu.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/mpu.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/random.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/random.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/random.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/sleep.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/sleep.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/sleep.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/token-def.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/generic/token-def.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/token-def.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/token.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/token.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/token.d
	@echo 'Finished building: $<'
	@echo ' '

hal-library/EM3588/uart.o: D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/platform/base/hal/micro/cortexm3/uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: IAR C/C++ Compiler for ARM'
	iccarm "$<" -o "$@" --no_path_in_file_macros --separate_cluster_for_initialized_variables -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3" -I"C:\Users\robbin\SimplicityStudio\v4_workspace\xncp-led_3\external-generated-files" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal//plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../CMSIS/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base//../radio/rail_lib/plugin" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/stack" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//protocol/zigbee/app/util" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/Device/SiliconLabs/em358x/Include" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/base/hal/micro/cortexm3/em35x/board" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/common" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/hal/em3xx" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/Config" -I"D:/SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7//util/third_party/segger/systemview/SEGGER" -e --use_c++_inline --cpu Cortex-M3 --fpu None --debug --dlib_config "D:/IARSystems/EmbeddedWorkbench7.80/arm/inc/c/DLib_Config_Normal.h" --endian little --cpu_mode thumb -Ohz --no_clustering '-DCORTEXM3=1' '-DCORTEXM3_EMBER_MICRO=1' '-DPHY_EM3XX=1' '-DSERIAL_UART_BTL=1' '-DCONFIGURATION_HEADER="ncp-configuration.h"' '-DCORTEXM3_EM3588=1' '-DCORTEXM3_EM3588_MICRO=1' '-DPLATFORM_HEADER="platform/base/hal/micro/cortexm3/compiler/iar.h"' '-DLOCKBITS_IN_MAINFLASH_SIZE=0' '-DPSSTORE_SIZE=0' '-DLONGTOKEN_SIZE=0' '-DBOARD_DEV0680UART=1' '-DBOARD_HEADER="ncp-board.h"' '-DUSE_SIMEE2=1' '-DEZSP_UART=1' '-DNO_USB=1' '-DEMLIB_USER_CONFIG=1' '-DEMBER_AF_NCP=1' '-DEMBER_STACK_ZIGBEE=1' '-DEMBER_AF_API_NEIGHBOR_HEADER="stack/include/stack-info.h"' '-DEMBER_SERIAL1_MODE=EMBER_SERIAL_BUFFER' '-DEMBER_SERIAL1_TX_QUEUE_SIZE=2' '-DEMBER_SERIAL1_RX_QUEUE_SIZE=64' '-DEMBER_SERIAL1_RTSCTS=1' '-DEMBER_SERIAL0_MODE=EMBER_SERIAL_FIFO' '-DEMBER_SERIAL0_TX_QUEUE_SIZE=64' '-DEMBER_SERIAL0_RX_QUEUE_SIZE=64' '-DAPPLICATION_TOKEN_HEADER="ncp-token.h"' '-DAPPLICATION_MFG_TOKEN_HEADER="ncp-mfg-token.h"' --diag_suppress Pa050 --dependencies=m hal-library/EM3588/uart.d
	@echo 'Finished building: $<'
	@echo ' '


