// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the XNCP Library plugin.
#include "../../../../../SiliconLabs/v4/developer/sdks/gecko_sdk_suite/v2.7/protocol/zigbee/app/xncp/xncp-token.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

