<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32pg22.prs" label="PRS" name="PRS" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="PRS.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="PRS.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="PRS.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="PRS.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="PRS.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH0.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH0_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch0_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH0.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH1.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH1_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch1_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH1.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH2.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH2_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch2_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH2.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH3.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH3_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch3_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH3.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH4.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH4_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch4_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH4.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH5.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH5_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch5_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH5.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH6.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH6_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch6_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH6.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH7.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH7_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch7_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH7.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH8.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH8_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch8_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH8.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH9.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH9_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch9_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH9.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH10.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH10_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch10_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH10.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH11.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH11_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="IADC0" value="IADC0"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="CORE" value="CORE"/>
        <enumValue label="CMUL" value="CMUL"/>
        <enumValue label="PRSL" value="PRSL"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="PDML" value="PDML"/>
        <enumValue label="EUART0" value="EUART0"/>
        <enumValue label="TIMER4" value="TIMER4"/>
        <enumValue label="LFRCO" value="LFRCO"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_CS" value="USART0_CS"/>
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_RXDATA" value="USART0_RXDATA"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_CS" value="USART1_CS"/>
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_RXDATA" value="USART1_RXDATA"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_IADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="IADC0_SCANENTRYDONE" value="IADC0_SCANENTRYDONE"/>
        <enumValue label="IADC0_SCANTABLEDONE" value="IADC0_SCANTABLEDONE"/>
        <enumValue label="IADC0_SINGLEDONE" value="IADC0_SINGLEDONE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_COMP" value="BURTC_COMP"/>
        <enumValue label="BURTC_OVERFLOW" value="BURTC_OVERFLOW"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_CORE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CORE_CTIOUT0" value="CORE_CTIOUT0"/>
        <enumValue label="CORE_CTIOUT1" value="CORE_CTIOUT1"/>
        <enumValue label="CORE_CTIOUT2" value="CORE_CTIOUT2"/>
        <enumValue label="CORE_CTIOUT3" value="CORE_CTIOUT3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_CMUL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMUL_CLKOUT0" value="CMUL_CLKOUT0"/>
        <enumValue label="CMUL_CLKOUT1" value="CMUL_CLKOUT1"/>
        <enumValue label="CMUL_CLKOUT2" value="CMUL_CLKOUT2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PRSL.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRSL_ASYNCH0" value="PRSL_ASYNCH0"/>
        <enumValue label="PRSL_ASYNCH1" value="PRSL_ASYNCH1"/>
        <enumValue label="PRSL_ASYNCH2" value="PRSL_ASYNCH2"/>
        <enumValue label="PRSL_ASYNCH3" value="PRSL_ASYNCH3"/>
        <enumValue label="PRSL_ASYNCH4" value="PRSL_ASYNCH4"/>
        <enumValue label="PRSL_ASYNCH5" value="PRSL_ASYNCH5"/>
        <enumValue label="PRSL_ASYNCH6" value="PRSL_ASYNCH6"/>
        <enumValue label="PRSL_ASYNCH7" value="PRSL_ASYNCH7"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_ASYNCH8" value="PRS_ASYNCH8"/>
        <enumValue label="PRS_ASYNCH9" value="PRS_ASYNCH9"/>
        <enumValue label="PRS_ASYNCH10" value="PRS_ASYNCH10"/>
        <enumValue label="PRS_ASYNCH11" value="PRS_ASYNCH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PDML.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PDML_PDMDSRPULSE" value="PDML_PDMDSRPULSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_EUART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="EUART0_IRDATX" value="EUART0_IRDATX"/>
        <enumValue label="EUART0_RTS" value="EUART0_RTS"/>
        <enumValue label="EUART0_TX" value="EUART0_TX"/>
        <enumValue label="EUART0_TXC" value="EUART0_TXC"/>
        <enumValue label="EUART0_RXFL" value="EUART0_RXFL"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER4.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER4_UF" value="TIMER4_UF"/>
        <enumValue label="TIMER4_OF" value="TIMER4_OF"/>
        <enumValue label="TIMER4_CC0" value="TIMER4_CC0"/>
        <enumValue label="TIMER4_CC1" value="TIMER4_CC1"/>
        <enumValue label="TIMER4_CC2" value="TIMER4_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_LFRCO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LFRCO_CALMEAS" value="LFRCO_CALMEAS"/>
        <enumValue label="LFRCO_SDM" value="LFRCO_SDM"/>
        <enumValue label="LFRCO_TCMEAS" value="LFRCO_TCMEAS"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch11_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH11.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="PRS">
        <subCategory label="">
          <propertyRef refId="PRS.usedbysdk.BOOL"/>
          <propertyRef refId="PRS.hiddenbysdk.BOOL"/>
          <propertyRef refId="PRS.showadvanced.BOOL"/>
          <propertyRef refId="PRS.forceenable.BOOL"/>
          <propertyRef refId="PRS.owner.STRING"/>
        </subCategory>
        <subCategory label="CH0 properties">
          <propertyRef refId="PRS.custom_name_CH0.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch0_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0.PIN"/>
        </subCategory>
        <subCategory label="CH1 properties">
          <propertyRef refId="PRS.custom_name_CH1.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch1_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1.PIN"/>
        </subCategory>
        <subCategory label="CH2 properties">
          <propertyRef refId="PRS.custom_name_CH2.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch2_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2.PIN"/>
        </subCategory>
        <subCategory label="CH3 properties">
          <propertyRef refId="PRS.custom_name_CH3.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch3_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3.PIN"/>
        </subCategory>
        <subCategory label="CH4 properties">
          <propertyRef refId="PRS.custom_name_CH4.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch4_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4.PIN"/>
        </subCategory>
        <subCategory label="CH5 properties">
          <propertyRef refId="PRS.custom_name_CH5.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch5_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5.PIN"/>
        </subCategory>
        <subCategory label="CH6 properties">
          <propertyRef refId="PRS.custom_name_CH6.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch6_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH6.PIN"/>
        </subCategory>
        <subCategory label="CH7 properties">
          <propertyRef refId="PRS.custom_name_CH7.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch7_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH7.PIN"/>
        </subCategory>
        <subCategory label="CH8 properties">
          <propertyRef refId="PRS.custom_name_CH8.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch8_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH8.PIN"/>
        </subCategory>
        <subCategory label="CH9 properties">
          <propertyRef refId="PRS.custom_name_CH9.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch9_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH9.PIN"/>
        </subCategory>
        <subCategory label="CH10 properties">
          <propertyRef refId="PRS.custom_name_CH10.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch10_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH10.PIN"/>
        </subCategory>
        <subCategory label="CH11 properties">
          <propertyRef refId="PRS.custom_name_CH11.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_IADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_CORE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_CMUL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PRSL.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PDML.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_EUART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER4.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_LFRCO.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch11_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH11.PIN"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
