<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32pg23.keyscan" label="KEYSCAN" name="KEYSCAN" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="KEYSCAN.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="KEYSCAN.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="KEYSCAN.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="KEYSCAN.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="KEYSCAN.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
    </properties>
    <propertyCategories>
      <category label="KEYSCAN">
        <subCategory label="">
          <propertyRef refId="KEYSCAN.usedbysdk.BOOL"/>
          <propertyRef refId="KEYSCAN.hiddenbysdk.BOOL"/>
          <propertyRef refId="KEYSCAN.showadvanced.BOOL"/>
          <propertyRef refId="KEYSCAN.forceenable.BOOL"/>
          <propertyRef refId="KEYSCAN.owner.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
